### ISSUE TITLE
Running linux git-seekret returns an error

### ISSUE THREAD

**Issue by alain-hoang** [18F/git-seekret#10]
When testing the linux version of `git-seekret`, the following error was being returned when running `git-seekret`

```
$ git-seekret
git-seekret: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by rogeruiz** [comment]
Good catch @alain-hoang! 👍 🎩 💁‍♂️ 

@LinuxBozo mentioned to me that `curl`/`libcurl` are usually not included in Linux distros, so we'll need to ensure that a few static libraries are installed for Linux.

- [x] `libcurl`
- [x] `libssh`
- [x] `libopenssl`
- [x] `libgit`

**Comment by rogeruiz** [comment]
For now though, let's ship the working Mac version and concentrate on getting 18F/laptop#69 merged into master. Specifically because the `18F/laptop` script is already pretty heavily dependant on a Mac environment in the first place. Linux compatibility is important though.

**Comment by LinuxBozo** [comment]
I think this can be closed now that https://github.com/18F/git-seekret/pull/12 has been merged and release updated.
