### ISSUE TITLE
Installer script issue on Linux (install path)

### ISSUE THREAD

**Issue by cmc333333** [18F/git-seekret#15]
The installer script tries to install the seekrets binary in `/usr/local/bin`, which isn't writable by non-root in Linux.

Potential solutions:
* ask for sudo permission if the path isn't writable - seems somewhat reasonable as this is a system-wide app
* ask the user where to install - probably too complicated for most users, but may be a reasonable fallback
* install in ~/bin and add it to the user's `PATH` (requires modifying bashrcs/etc.) - doesn't seem worth the effort and is error prone, but would be the most friendly.

**Comment by LinuxBozo** [comment]
Should be closed by https://github.com/18F/laptop/pull/130

**Comment by LinuxBozo** [comment]
Hybrid approach used in above PR:
If user has `~/bin` in their path already, will install there. If not, will install in `/usr/local/bin` with `sudo` required.

@cmc333333 Can you verify?

**Comment by cmc333333** [comment]
Tested: 
* `~/bin` in my path (installs to ~/bin correctly)
* `~/bin` not in my path (installed to `/usr/local/bin`). Vagrant doesn't require a password for sudo, so I didn't actually test that prompt.

Content to close this, though, thanks!
