### ISSUE TITLE
Installer script popd issue in later versions of bash

### ISSUE THREAD

**Issue by cmc333333** [18F/git-seekret#16]
```bash
./seekrets-install: line 93: popd: /tmp/tmp.7kBP85AYOb: invalid argument
popd: usage: popd [-n] [+N | -N]
```
I don't see it in osx: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

But do on debian: GNU bash, version 4.4.5(1)-release (x86_64-pc-linux-gnu)

**Comment by LinuxBozo** [comment]
Should be closed by https://github.com/18F/laptop/pull/130

**Comment by LinuxBozo** [comment]
@cmc333333 Can you verify now that above PR has been merged?

**Comment by cmc333333** [comment]
Yeppa, all looks good. Thanks!
