### ISSUE TITLE
[ Proposed feature ] enable and disable checks in repos

### ISSUE THREAD

**Issue by alain-hoang** [18F/git-seekret#8]
This is a proposal to have a feature in git-seekret that can enable or disable particular types of checks on a per repository basis.  Some possible types of checks include checking staged files, checking all commits in a repository.

### Acceptance Criteria

- [ ] Enabled check features are added to the configuration settings for git-seekret in the local `./.git/config` file.
- [ ] TBD

### Interaction Sketch

To enable checking of staged files

`git-seekret check --enable staged`

To disable checking of staged files:

`git-seekret check --disable-staged`

**Comment by LinuxBozo** [comment]
Closing as not necessary..
You want staged files, use `--staged`. If you don't want staged files, use `--commit`.
